### ISSUE TITLE
自定义头部视图

### ISSUE THREAD

**Issue by Simon1121** [qdxxxx/StickyHeaderDecoration#2]
grid的时候，例如你的demo，怎么让每张图片横向居中。本来想设置match_parent让它居中的，结果当一行不满的时候，最后一个item会沾满整行

**Comment by sorrybeman** [comment]
同样遇到了“当一行不满的时候，最后一个item会沾满整行”， 可以设置给item设置一个固定的值，但不是很符合要求

**Comment by qdxxxx** [comment]
#4
