### ISSUE TITLE
我的GridDecoration的分组的最后一个Item会占满所有空白的地方

### ISSUE THREAD

**Issue by sorrybeman** [qdxxxx/StickyHeaderDecoration#4]
`<?xml version="1.0" encoding="utf-8"?>
<layout>

    <data>

        <variable
            name="viewmodel"
            type="com.raysharp.camviewplus.file.FileItemViewModel" />
    </data>

    <RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
        android:layout_width="match_parent"
        android:layout_height="160dp"
        android:background="@color/colorAccent">

        <ImageView
            android:id="@+id/iv_cover"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_alignParentStart="true"
            android:layout_alignParentTop="true"
            android:scaleType="fitCenter"
            android:src="@drawable/ic_about" />

        <ImageView
            android:id="@+id/iv_select"
            android:layout_width="50dp"
            android:layout_height="50dp"
            android:layout_alignParentBottom="true"
            android:layout_alignParentEnd="true"
            android:src="@drawable/ic_select_all" />

        <TextView
            android:id="@+id/tv_file_message"
            android:layout_width="100dp"
            android:layout_height="50dp"
            android:layout_alignParentBottom="true"
            android:layout_alignParentStart="true"
            android:gravity="center"
            android:text="@{viewmodel.itemData.createDate}" />
    </RelativeLayout>

</layout>
`
这是itemlayout.xml文件

![image](https://user-images.githubusercontent.com/20702156/43819013-d3675338-9b13-11e8-88bc-b7c4845427c4.png)

**Comment by sorrybeman** [comment]
我已经发现问题所在了 其实demo也会占用一行 只不过是套了一层壳

**Comment by qdxxxx** [comment]
这个和StickyHeaderDecoration关系不大，因为这个库是RecyclerView.addItemDecoration,添加的装饰品, 
使用GridLayoutManager并且Adapter 的 item背景为图片的建议是动态计算并设置item的宽高。
